// Amalgamated header generated from spacetree.h
// DO NOT EDIT THIS FILE MANUALLY
// Changes will be overwritten by amalgamate.sh
#pragma once

// #include <erased/erased.h>
// BEGIN erased/erased.h
#pragma once

// #include "utils/utils.h"
// BEGIN utils/utils.h
#pragma once

#include <array>
#include <tuple>
#include <type_traits>

namespace erased::details {
struct erased_type_t {};

template <bool condition> struct fast_conditional {
  template <typename T, typename F> using apply = T;
};

template <> struct fast_conditional<false> {
  template <typename T, typename F> using apply = F;
};

template <typename Method, typename F> struct method_to_trait;

template <typename Method, typename ErasedType, typename ReturnType,
          typename... Args>
struct method_to_trait<Method, ReturnType (*)(ErasedType &, Args...)> {
  static constexpr bool is_const = std::is_const_v<ErasedType>;

  using first_argument =
      typename fast_conditional<is_const>::template apply<const void *, void *>;

  using type = ReturnType (*)(first_argument, Args...);

  template <typename T> static constexpr auto create_invoker_for() {
    return +[](first_argument first, Args... args) {
      if constexpr (is_const) {
        return Method::invoker(*static_cast<const T *>(first),
                               static_cast<Args &&>(args)...);
      } else {
        return Method::invoker(*static_cast<T *>(first),
                               static_cast<Args &&>(args)...);
      }
    };
  }
};

template <typename Method>
using method_to_trait_t =
    method_to_trait<Method, decltype(&Method::template invoker<erased_type_t>)>;

template <typename Method>
using method_ptr = typename method_to_trait_t<Method>::type;

template <typename Method, typename... Methods> constexpr int index_in_list() {
  std::array array = {std::is_same_v<Method, Methods>...};
  for (int i = 0; i < static_cast<int>(array.size()); ++i)
    if (array[i])
      return i;
  return -1;
}

template <typename... Methods> struct vtable {
  constexpr vtable(method_ptr<Methods>... ptrs) : m_functions{ptrs...} {}

  template <typename T>
  static constexpr const vtable *construct_for() noexcept {
    static constexpr vtable vtable(
        method_to_trait_t<Methods>::template create_invoker_for<T>()...);
    return &vtable;
  }

  template <typename Method> constexpr auto *get() const noexcept {
    constexpr int index = index_in_list<Method, Methods...>();
    return std::get<index>(m_functions);
  }

  std::tuple<method_ptr<Methods>...> m_functions;
};
} // namespace erased::details
// END utils/utils.h
#include <array>
#include <new>
#include <typeinfo>
#include <utility>

#define fwd(x) static_cast<decltype(x) &&>(x)

namespace erased {

struct Copy {
  template <typename T>
  static constexpr void *invoker(const T &object, void *sooPtr,
                                 std::size_t sooSize) {
    if (sizeof object > sooSize || std::is_constant_evaluated())
      return new T{object};
    else {
      return new (sooPtr) T{object};
    }
  }
};

struct Move {
  template <typename T>
  static constexpr void *invoker(T &object, void *sooPtr, std::size_t sooSize) {
    if (sizeof object > sooSize || std::is_constant_evaluated())
      return new T{std::move(object)};
    else {
      return new (sooPtr) T{std::move(object)};
    }
  }
};

namespace details {
template <typename Soo> struct Destructor {
  template <typename T> static constexpr void invoker(T &, Soo *soo) {
    soo->template destroy<T>();
  }
};

template <int Size, typename... Methods> struct soo {
  using vtable = details::vtable<Methods..., Destructor<soo>>;
  static constexpr auto buffer_size =
      Size - sizeof(void *) - sizeof(const vtable *);
  std::array<std::byte, buffer_size> m_buffer;
  void *ptr = nullptr;
  const vtable *vtable_ptr = nullptr;

  template <typename T, typename... Args>
  constexpr T *construct(Args &&...args) {
    static_assert(sizeof(soo) == Size);
    if constexpr (sizeof(T) <= buffer_size) {
      if (std::is_constant_evaluated()) {
        ptr = new T{fwd(args)...};
      } else {
        ptr = new (m_buffer.data()) T{fwd(args)...};
      }
    } else {
      ptr = new T{fwd(args)...};
    }
    vtable_ptr = vtable::template construct_for<T>();
    return static_cast<T *>(ptr);
  }

  template <typename T> constexpr T *get() noexcept {
    return static_cast<T *>(ptr);
  }

  template <typename T> constexpr const T *get() const noexcept {
    return static_cast<const T *>(ptr);
  }

  template <typename T> constexpr void destroy() noexcept {
    T *ptr = get<T>();
    if constexpr (sizeof(T) <= buffer_size) {
      if (std::is_constant_evaluated()) {
        delete ptr;
      } else {
        std::destroy_at(ptr);
      }
    } else {
      delete ptr;
    }
  }
};

template <typename T, typename... List> constexpr bool contains() {
  return (std::is_same_v<T, List> || ...);
}
} // namespace details

template <int Size, typename... Methods> struct basic_erased;

template <typename T> struct is_erased : std::false_type {};

template <int Size, typename... Methods>
struct is_erased<basic_erased<Size, Methods...>> : std::true_type {};

template <typename T> constexpr bool is_erased_v = is_erased<T>::value;

template <typename T>
concept erased_concept = is_erased_v<std::decay_t<T>>;

template <int Size, typename... Methods>
struct alignas(Size) basic_erased : public Methods... {
  using soo = details::soo<Size, Methods...>;

  static constexpr bool copyable = details::contains<Copy, Methods...>();
  static constexpr bool movable = details::contains<Move, Methods...>();

  template <typename T>
  constexpr basic_erased(std::in_place_type_t<T>, auto &&...args) noexcept {
    m_soo.template construct<T>(fwd(args)...);
  }

  template <typename T>
  constexpr basic_erased(T x) noexcept
      : basic_erased{std::in_place_type<T>, static_cast<T &&>(x)} {}

  template <typename Method>
  constexpr decltype(auto) invoke(Method, auto &&...xs) const {
    return m_soo.vtable_ptr->template get<Method>()(
        static_cast<const void *>(m_soo.ptr), fwd(xs)...);
  }

  template <typename Method>
  constexpr decltype(auto) invoke(Method, auto &&...xs) {
    return m_soo.vtable_ptr->template get<Method>()(m_soo.ptr, fwd(xs)...);
  }

  constexpr basic_erased(basic_erased &&other) noexcept
    requires movable
  {
    m_soo.vtable_ptr = other.m_soo.vtable_ptr;
    m_soo.ptr = other.invoke(Move{}, static_cast<void *>(m_soo.m_buffer.data()),
                             soo::buffer_size);
  }

  constexpr basic_erased &operator=(basic_erased &&other) noexcept
    requires movable
  {
    destroy();
    m_soo.vtable_ptr = other.m_soo.vtable_ptr;
    m_soo.ptr = other.invoke(Move{}, static_cast<void *>(m_soo.m_buffer.data()),
                             soo::buffer_size);
    return *this;
  }

  constexpr basic_erased(const basic_erased &other)
    requires copyable
  {
    m_soo.vtable_ptr = other.m_soo.vtable_ptr;
    m_soo.ptr = other.invoke(Copy{}, static_cast<void *>(m_soo.m_buffer.data()),
                             soo::buffer_size);
  }

  constexpr basic_erased &operator=(const basic_erased &other)
    requires copyable
  {
    destroy();
    m_soo.vtable_ptr = other.m_soo.vtable_ptr;
    m_soo.ptr = other.invoke(Copy{}, static_cast<void *>(m_soo.m_buffer.data()),
                             soo::buffer_size);
    return *this;
  }

  constexpr void destroy() {
    invoke(details::Destructor<decltype(m_soo)>{}, &m_soo);
  }

  constexpr ~basic_erased() { destroy(); }

  template <typename T, int S, typename... M>
  friend constexpr bool is(const basic_erased<S, M...> &object);

  template <typename T, erased_concept Erased>
  friend constexpr auto *any_cast(Erased *object);

  template <typename T, erased_concept Erased>
  friend constexpr auto &&any_cast(Erased &&object);

private:
  soo m_soo;
};

template <typename... Methods> using erased = basic_erased<32, Methods...>;

template <typename T, int Size, typename... Methods>
constexpr bool is(const basic_erased<Size, Methods...> &object) {
  using soo = typename basic_erased<Size, Methods...>::soo;
  using vtable = typename soo::vtable;

  return object.m_soo.vtable_ptr == vtable::template construct_for<T>();
}

template <typename T, erased_concept Erased>
constexpr auto *any_cast(Erased *object) {
  if (is<T>(*object))
    return object->m_soo.template get<T>();
  return decltype(object->m_soo.template get<T>()){nullptr};
}

template <typename T, erased_concept Erased>
constexpr auto &&any_cast(Erased &&object) {
  if (is<T>(object))
    return std::forward_like<Erased>(*object.m_soo.template get<T>());
  throw std::bad_cast();
}
} // namespace erased

#undef fwd

#define ERASED_HEAD(a, ...) a
#define ERASED_TAIL(a, ...) __VA_ARGS__
#define ERASED_EAT(...)
#define ERASED_EXPAND(...) __VA_ARGS__

#define ERASED_REMOVE_PARENTHESIS_IMPL(...) __VA_ARGS__
#define ERASED_REMOVE_PARENTHESIS(...)                                         \
  ERASED_EXPAND(ERASED_REMOVE_PARENTHESIS_IMPL __VA_ARGS__)

#define ERASED_ADD_COMA_AFTER_PARENTHESIS_IMPL(...) (__VA_ARGS__),
#define ERASED_ADD_COMA_AFTER_PARENTHESIS(...)                                 \
  (ERASED_EXPAND(ERASED_ADD_COMA_AFTER_PARENTHESIS_IMPL __VA_ARGS__))

#define ERASED_REMOVE_AFTER_PARENTHESIS(...)                                   \
  ERASED_REMOVE_PARENTHESIS(                                                   \
      ERASED_HEAD ERASED_ADD_COMA_AFTER_PARENTHESIS(__VA_ARGS__))

#define ERASED_CAT_IMPL(a, b) a##b
#define ERASED_CAT(...) ERASED_CAT_IMPL(__VA_ARGS__)
#define ERASED_GET_AFTER_requires(...) (__VA_ARGS__)
#define ERASED_GET_INSIDE_REQUIRES(...)                                        \
  ERASED_REMOVE_AFTER_PARENTHESIS(                                             \
      ERASED_CAT(ERASED_GET_AFTER_, ERASED_EAT __VA_ARGS__))

#define ERASED_GET_TRAILING_RETURN(...)                                        \
  ERASED_EXPAND(ERASED_TAIL ERASED_ADD_COMA_AFTER_PARENTHESIS(                 \
      ERASED_CAT(ERASED_GET_AFTER_, ERASED_EAT __VA_ARGS__)))

#define ERASED_MAKE_BEHAVIOR(Name, name, signature)                            \
  struct Name {                                                                \
    static constexpr auto                                                      \
    invoker(auto ERASED_REMOVE_AFTER_PARENTHESIS(signature))                   \
        ERASED_GET_TRAILING_RETURN(signature) {                                \
      return ERASED_GET_INSIDE_REQUIRES(signature);                            \
    }                                                                          \
                                                                               \
    constexpr decltype(auto) name(this auto &&self, auto &&...args) {          \
      return self.invoke(Name{}, static_cast<decltype(args) &&>(args)...);     \
    }                                                                          \
  }

#undef fwd
// END erased/erased.h

#include <optional>

template <typename T>
struct matrix_trait
{
    static_assert(false, "Must be implemented for your own matrix type");
    static void set_identity(T& self);
    static T multiply(const T& self, const T& other);
};

namespace spacetree
{

    namespace details
    {

        struct Identity;
        struct Multiply;
        using Transformable = erased::erased<Identity, Multiply, erased::Copy, erased::Move>;

        struct Identity
        {
            constexpr static void invoker(auto& self)
            {
                using SelfType = std::remove_cvref_t<decltype(self)>;
                matrix_trait<SelfType>::set_identity(self);
            }

            constexpr void set_identity(this auto& erased)
            {
                return erased.invoke(Identity{});
            }
        };

        struct Multiply
        {
            constexpr static std::optional<Transformable> invoker(const auto& self, const Transformable& other)
            {
                using SelfType = std::remove_cvref_t<decltype(self)>;
                if (erased::is<SelfType>(other))
                    return matrix_trait<SelfType>::multiply(self, erased::any_cast<SelfType>(other));
                return std::nullopt;
            }

            constexpr std::optional<Transformable> multiply(this const auto& erased, const Transformable& other)
            {
                return erased.invoke(Multiply{}, other);
            }
        };

    }

    struct Node
    {
        constexpr Node() = default;

        template <typename T, typename... Args>
        constexpr Node(std::in_place_type_t<T>, Args&&... args)
            : _transform(std::in_place, std::in_place_type<T>, std::forward<Args>(args)...)
        {
            _transform->set_identity();
        }

        template <typename T>
        constexpr Node(T x)
            : Node{ std::in_place_type<T>, std::forward<T>(x) }
        {
        }

        constexpr ~Node() = default;
        constexpr Node(const Node&) = default;
        constexpr Node(Node&&) = default;
        constexpr Node& operator=(const Node&) = default;
        constexpr Node& operator=(Node&&) = default;

        constexpr std::optional<details::Transformable> transform_to(const Node& other) const
        {
            if (std::addressof(other) == this)
                return _transform;
            return std::nullopt;
        }

    private:
        std::optional<details::Transformable> _transform{ std::nullopt };
    };

}
