#!/bin/bash

SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
SOURCE_DIR=$(realpath ${SCRIPT_DIR}/..)

SPACETREE_HEADER="$SOURCE_DIR/include/spacetree/spacetree.h"
ERASED_HEADER="$ERASED_DIR/erased/include/erased/erased.h"
ERASED_UTILS_HEADER="$ERASED_DIR/erased/include/erased/utils/utils.h"

OUTPUT="$SOURCE_DIR/include/spacetree/spacetree_amalgamated.h"

echo "// Amalgamated header generated from spacetree.h" > "$OUTPUT"
echo "// DO NOT EDIT THIS FILE MANUALLY" >> "$OUTPUT"
echo "// Changes will be overwritten by amalgamate.sh" >> "$OUTPUT"

while IFS= read -r line; do
    if [[ "$line" == "#include <erased/erased.h>" ]]; then
        echo "// $line" >> "$OUTPUT"
        echo "// BEGIN erased/erased.h" >> "$OUTPUT"

        while IFS= read -r eline; do
            if [[ "$eline" == "#include \"utils/utils.h\"" ]]; then
                echo "// $eline" >> "$OUTPUT"
                echo "// BEGIN utils/utils.h" >> "$OUTPUT"
                cat "$ERASED_UTILS_HEADER" >> "$OUTPUT"
                echo "// END utils/utils.h" >> "$OUTPUT"
            else
                echo "$eline" >> "$OUTPUT"
            fi
        done < "$ERASED_HEADER"

        echo "// END erased/erased.h" >> "$OUTPUT"
    else
        echo "$line" >> "$OUTPUT"
    fi
done < "$SPACETREE_HEADER"
