name: CMake on multiple platforms

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  build:
    permissions:
      packages: write

    env:
      USERNAME: theo-dep
      #VCPKG_ROOT: ${{ env.VCPKG_INSTALLATION_ROOT }}/vcpkg
      FEED_URL: https://nuget.pkg.github.com/theo-dep/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/theo-dep/index.json,readwrite"

    name: ${{ matrix.os }}-${{ matrix.cxx_compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cxx_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            cxx_compiler: cl
            c_compiler: cl
            mono: ""
          - os: windows-latest
            cxx_compiler: clang++
            c_compiler: clang
            mono: ""
          - os: ubuntu-latest
            cxx_compiler: g++
            c_compiler: gcc
            mono: mono
          - os: ubuntu-latest
            cxx_compiler: clang++
            c_compiler: clang
            mono: mono
          - os: macos-latest
            cxx_compiler: clang++
            c_compiler: clang
            mono: mono
        exclude:
          - os: windows-latest
            cxx_compiler: g++
          - os: ubuntu-latest
            cxx_compiler: cl
          - os: macos-latest
            cxx_compiler: g++
          - os: macos-latest
            cxx_compiler: cl

    steps:
      - uses: actions/checkout@v5

      - name: Add vcpkg to PATH
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
          echo "$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_PATH"

      - name: Bootstrap vcpkg
        shell: bash
        run: |
          git -C $VCPKG_ROOT fetch
          $VCPKG_ROOT/bootstrap-vcpkg.sh

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y mono-complete autoconf autoconf-archive automake libtool

      - name: Install macOS build dependencies
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install mono autoconf automake autoconf-archive libtool

      - name: Add NuGet sources
        shell: bash
        run: |
          ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1` \
            sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"

      - name: Configure and Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: vcpkg
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}', '-DCMAKE_C_COMPILER=${{ matrix.c_compiler }}']"
          buildPreset: vcpkg
          testPreset: vcpkg
          testPresetAdditionalArgs: "['--output-junit tests.xml']"

      - name: Publish test results
        uses: mikepenz/action-junit-report@v5
        if: ${{ !cancelled() }}
        with:
          report_paths: build/vcpkg/tests.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.cxx_compiler }}
          path: build/vcpkg/tests.xml
          retention-days: 7
